import { motion, AnimatePresence } from "framer-motion";
import { Terminal } from "lucide-react";

interface BottomConsoleProps {
    traces: string[];
    status: string;
}

export function BottomConsole({ traces, status }: BottomConsoleProps) {
    return (
        <div className="fixed bottom-0 left-0 right-0 h-[30vh] bg-[#121212] border-t border-[#2A2A2A] flex flex-col font-mono z-40">
            <div className="flex items-center justify-between px-4 py-2 bg-[#1A1A1A] border-b border-[#2A2A2A]">
                <div className="flex items-center gap-2 text-xs text-[#A0A0A0]">
                    <Terminal size={14} />
                    <span>REASONING TRACE</span>
                </div>
                <div className="text-xs font-medium text-[#10B981]">
                    {status === "COMPLETE" ? "SAFETY_SCORE: 96 / 100" : ""}
                </div>
            </div>
            <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
                <AnimatePresence>
                    {traces.map((trace, i) => {
                        const isError = trace.includes("ERROR") || trace.includes("FAILED");
                        const isSuccess = trace.includes("SUCCESS") || trace.includes("OK");
                        const isDetect = trace.includes("DETECT") || trace.includes("REPLACE");

                        return (
                            <motion.div
                                key={i}
                                initial={{ opacity: 0, x: -10 }}
                                animate={{ opacity: 1, x: 0 }}
                                className={`text-sm mb-1 ${isError ? 'text-[#ED1C24]' :
                                    isSuccess ? 'text-[#10B981]' :
                                        isDetect ? 'text-[#3B82F6]' :
                                            'text-[#A0A0A0]'
                                    }`}
                            >
                                {trace}
                            </motion.div>
                        );
                    })}
                    {status === "COMPLETE" && (
                        <motion.div
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ delay: 0.5 }}
                            className="mt-4 pt-2 border-t border-[#2A2A2A] text-xs text-[#606060]"
                        >
                            Trace generated by Forge AI on MI300X · ForgeX
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
}
